### ISSUE TITLE
Re -Write  Organization Management Page in the React UI

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#1005]
https://oe3.openelis-global.org/api/OpenELIS-Global/OrganizationMenu

**Comment by mherman22** [comment]
@mozzy11 assign me to this

**Comment by adityadeshlahre** [comment]
Hey @mozzy11 would like to get this issues assigned :slightly_smiling_face: Thank You

**Comment by adityadeshlahre** [comment]
## Update

![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/132184385/10d64c17-079f-477d-8fb9-b6cd0f2a314c)


- converted MVC controller to RestController
- currently only GET request is working [need to test all the POST/GET calls]

**Comment by mozzy11** [comment]
Thanks @adityadeshlahre for the great work
