### ISSUE TITLE
Re write Site Information Page in the new UI

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#1008]
see Old page  https://oe3.openelis-global.org/api/OpenELIS-Global/SiteInformationMenu

**Comment by mozzy11** [comment]
This depends on https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/1012

**Comment by Isabirye1515** [comment]
i would like to take up this issue but its to abstacted in that the linked page has more that is linked to it that also have to be changed should we focus on the that page alone
