### ISSUE TITLE
GSOC 2024 : Improve End To End Tests coverage

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#1032]
# Reporting an Issue with OpenELIS Global

If you encounter an issue with OpenELIS Global, please make a [new issue](https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/new) and include the following information:

1. Note the section, tab, or page of OpenELIS that is affected by your issue. For example, *Patient -> Add/Edit Patient page -> Search Patient Form*

2. Describe in detail the steps you were followed to encounter the issue. For example, *I scanned the accession number barcode, then entered the order information. When I tried to add a sample type for Whole Blood, the system returned an error message that stated: SYSTEM ERROR 523. This did not happen when I added other sample types Plasma and Serum.*

3. Include the url where you encountered the bug. For example, https://openelis28.openelis-global.org/PatientManagement

4. Attach relevant screenshots and video recordings if necessary.

5. Indicate the severity of the issue using the following ratings:
    1. This issue is something we would like to see improved in the future but does not significantly affect our work.
    2. This issue makes OpenELIS slow, difficult, or confusing, but we are able to keep working with it.
    3. This issue prevents us from using OpenELIS

**Comment by manishjha-04** [comment]
Hey @mozzy11  I would like to work on this!
