### ISSUE TITLE
Rewrite Analyzer Test Names in new react UI 

### ISSUE THREAD

**Issue by manishjha-04** [I-TECH-UW/OpenELIS-Global-2#1132]
**Current Status:**
I am currently working on this task and will provide updates as progress

**Comment by adityadeshlahre** [comment]
Hey @manishjha-04 

can u share the route and image of the PAGE ?

Thank You :slightly_smiling_face:

**Comment by manishjha-04** [comment]
Sure Here it is 
![Screenshot 2024-06-23 221722](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/51dd178d-b082-4958-8bd0-f1f6e4af1300)
