### ISSUE TITLE
Iprove Responsivenes for the Global Search bar on the main Menu bar

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#1249]
See attached screen shots
on a Desktop screen
![image](https://github.com/user-attachments/assets/56d8eab5-8878-433f-a8fe-4d7a021fdefa)

on a small screen 
![image](https://github.com/user-attachments/assets/29c3221e-c7fa-48bd-b184-80c2af909229)

**Comment by Bahati308** [comment]
hello @mozzy11 , can i work on this issue

**Comment by mozzy11** [comment]
Yeah @Bahati308

**Comment by Bahati308** [comment]
hello @mozzy11 , any advice on this https://github.com/Bahati308/OpenELIS-Global-2 ?? thanks

**Comment by mozzy11** [comment]
hello @Bahati308 , can you create a Pull Request ?

**Comment by Bahati308** [comment]
hello @mozzy11 , here it is sir 
https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/1294

**Comment by Bahati308** [comment]
hello @mozzy11, how do you see if we close this issue??

**Comment by parthshah02** [comment]
Please assign me this issue !

**Comment by mozzy11** [comment]
Thanks @Parth20GitHub .
This isse has been work on . can you try another issue ??

**Comment by parthshah02** [comment]
Hello, @mozzy11 Please checkout #1305 issue
