### ISSUE TITLE
Improve styling for the AutoComplete Component 

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#1250]
We use a common resubale [AutoComple](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/frontend/src/components/common/AutoComplete.js) component on multiple pages. 
But the Suggestion List doesnt display properly on different pages ie it has a fixed width. it should have a dynamic width

see on Add order Page
![image](https://github.com/user-attachments/assets/364f050c-98bc-476f-aa23-442b9c3e2917)

see on Reflex test management Page
![image](https://github.com/user-attachments/assets/c2195055-df60-4de7-8054-da2bd984e27a)

**Comment by sakshamgupta912** [comment]
@mozzy11 I'd like to work on this. Could you assign it to me?

**Comment by sakshamgupta912** [comment]
@mozzy11 Kindly check my PR https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/1290 for this issue

**Comment by mozzy11** [comment]
Thanks @sakshamgupta912 .
The wodth is fixed but the problem is it now causes a Layout shift.
ive pushed a fowwloup fix https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/1291
