### ISSUE TITLE
Fix Responsivenes of the Patient Header Display component

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#1254]
We use a Re-Usable [Patient Header ](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/frontend/src/components/common/PatientHeader.js)display component on multiple Pages  ie on Patient Histroy , Edit Order etc
.WE need to improve ints responsivenes on smaller screen sizes.
see atcched screen shot on the Patient History page

Desktop view
![image](https://github.com/user-attachments/assets/951a605e-02cb-4a50-9227-7c88aefd9207)

Mobile View
![image](https://github.com/user-attachments/assets/71078503-37c0-4440-967e-d0160d3b0f80)

**Comment by Isabirye1515** [comment]
[Screencast from 16-09-24 15:18:06.webm](https://github.com/user-attachments/assets/ad46b2ca-2c22-4b82-af3a-6262e9967a84)

**Comment by samr874** [comment]
@mozzy11 Are the contributions still active ?? I am a full stack java developer looking towards further modifications for this project ??

**Comment by Isabirye1515** [comment]
[Screencast from 09-10-24 15:15:30.webm](https://github.com/user-attachments/assets/0988e104-3009-4ec7-a34a-d978ce0b4083)
@mozzy11  sir have made these changes and i require your reproof

**Comment by mozzy11** [comment]
Thanks @Isabirye1515

**Comment by Isabirye1515** [comment]
thanks sir , u know you once said "if it has to be done, it has to be done well"
