### ISSUE TITLE
Learn More Button 

### ISSUE THREAD

**Issue by parthshah02** [I-TECH-UW/OpenELIS-Global-2#1305]
The alignment of the button is improper,

![image](https://github.com/user-attachments/assets/01715c84-6c3d-41ce-8acc-025617650c77)

Please assign this task to me

**Comment by mozzy11** [comment]
Can you add more description of the issues especially how to reproduce it ??

**Comment by parthshah02** [comment]
the move down icon overlaps the box sizing, increasing the size of section would help it

**Comment by mozzy11** [comment]
How can some one reproduce it ??
Can you be soecific on where that is found on the application ?
