### ISSUE TITLE
Fix bug on checkbox selection on the test notification config menu

### ISSUE THREAD

**Issue by mherman22** [I-TECH-UW/OpenELIS-Global-2#1322]
The behaviour in the video is not ideal. We will need to handle it better like the way the old ui was handling it.

https://github.com/user-attachments/assets/eef9b118-322e-4a80-80d8-0206d6ae1caf

**Comment by Vineet1101** [comment]
Can you explain which type of behaviour you want
@pmanko can you tell me more about this issue

**Comment by mherman22** [comment]
The behaviour at https://testing.openelis-global.org/api/OpenELIS-Global/TestNotificationConfigMenu is the ideal

**Comment by Vineet1101** [comment]
Ok I think it could be an issue with css

**Comment by Vineet1101** [comment]
Can you help me setup the it locally so that i can work on it @mherman22

**Comment by mherman22** [comment]
have you read through https://github.com/I-TECH-UW/OpenELIS-Global-2?tab=readme-ov-file#running-openelis-global2-using-docker-compose-with-locally-compiledbuilt-artifacts-ie-the-war-file-and-react-code?

**Comment by Vineet1101** [comment]
@mherman22 Thanks for telling let me setup the project locally and then I'll start working on it

**Comment by adityadeshlahre** [comment]
Nice catch @mherman22 :slightly_smiling_face:
