### ISSUE TITLE
 Issue with Billing Module - Menu Item Doesn't Load Any Page

### ISSUE THREAD

**Issue by pascagihozo** [I-TECH-UW/OpenELIS-Global-2#1326]
# Reporting an Issue with OpenELIS Global

If you encounter an issue with OpenELIS Global, please make a
[new issue](https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/new) and
include the following information:

1. **Section, Tab, or Page Affected:** Main Menu -> Billing

2. **Steps to Reproduce the Issue:** 
   1. Logged into OpenELIS, 2. Clicked Menu, 3. Clicked Billing, 4. Observed that clicking the "Billing" menu does not navigate to 
any page or load any functionality. The screen remains unchanged.

3.**URL Encountered:**  (https://localhost/billing)

5.**Screen record:**

https://github.com/user-attachments/assets/e67343ed-257e-430a-a7ab-66edeb6cf98f

6. This issue prevents us from using OpenELIS billing

**Comment by mherman22** [comment]
are you able to reproduce that here https://testing.openelis-global.org/?

**Comment by kssampath** [comment]
Hello, Please assign me this ticket.

**Comment by mozzy11** [comment]
I think this is not an issue. 
Currently that URL is configurable and should be set to point to the right instance
