### ISSUE TITLE
Modify Tests Page not loading anything

### ISSUE THREAD

**Issue by nsalifu** [I-TECH-UW/OpenELIS-Global-2#1327]
# Reporting an Issue with OpenELIS Global

If you encounter an issue with OpenELIS Global, please make a
[new issue](https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/new) and
include the following information:

1. Note the section, tab, or page of OpenELIS that is affected by your issue.
   Admin->Test Management->Modify Tests 

2. Describe in detail the steps you were followed to encounter the issue. 
	Before updating to use 3.1.0 release of the lateat wepapp image from dockerhub,    I was able to visit modify tests page and add 			 LOIC codes to the existing tests.   Today it's no longer the case.   Thesame page does not load any test that is it's just a blank page.  

3. Attach relevant screenshots and video recordings if necessary.   This is openelis 3.1.0.0

![Screenshot 2024-11-25 at 15 19 18](https://github.com/user-attachments/assets/99362eff-6f68-4477-a5f6-5e9aff728dff)

Here is openelis 2.8.1.22.  and it's working fine.

![Screenshot 2024-11-25 at 17 09 36](https://github.com/user-attachments/assets/4e90c38b-8d23-4691-acb6-f6fc15716cd1)

6. Indicate the severity of the issue using the following ratings:
    This issue prevents us from using OpenELIS

**Comment by nsalifu** [comment]
@mozzy11  @Agaba-derrick  @mherman22

**Comment by njiddasalifu** [comment]
thanks for the fix @mozzy11 . 
here is the PR addressing the ticket: https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/1328
