### ISSUE TITLE
[BUG] The Billing option on the dropdown menu leads to the home page and then to MasterListsPage just as does the Admin option

### ISSUE THREAD

**Issue by Bahati308** [I-TECH-UW/OpenELIS-Global-2#1341]
menu --- -> Billing
  menu -----> Admin

 [first time leads to the home page and while on the home page, going back to the menu and selecting billing again, leads to the MasterListsPage. And going back to the menu button and selecting Admin, leads to the same MasterListsPage ]

 Attached is the video recording
[Screencast from 2024-12-06 17-21-47.webm](https://github.com/user-attachments/assets/4f20e71b-58fb-45fb-82a0-02fff069e1fd)

The severity of the issue 
   1. This issue is something we would like to see improved in the future but
      does not significantly affect our work.

**Comment by vedsb** [comment]
hello i can fix the issue could u plz assign

**Comment by Bahati308** [comment]
yes @vedsb  please take it up,

**Comment by Nirvanjha2004** [comment]
@vedsb @Bahati308 Whats the update on this issue... If the issue needs attention.... can i take up this ??

**Comment by vedsb** [comment]
@Bahati308 @Nirvanjha2004 i guess the bug is fixed as i cant see it  .
