### ISSUE TITLE
Error while building OpenELIS-Global-2 project.

### ISSUE THREAD

**Issue by Ruhanga** [I-TECH-UW/OpenELIS-Global-2#158]
Hi here,

I'm trying to build and run OpenELIS-Global-2 while following t[his guide](https://talk.openelisci.org/t/how-to-run-openelis-from-source-code/17/2). I am getting the error below when I run `sudo mvn clean install dockerfile:build`:

`[ERROR] Failed to execute goal on project openelisglobal: Could not resolve dependencies for project org.openelisglobal:openelisglobal:war:1.0.0.0: Could not find artifact org.itech:dataexport-api:jar:0.0.0.1`

How can I go about resolving this? Looks like the artifact was never published to maven, I also tried installing the `dataexport` project but failed to proceed with the same error. Thanks in advance for the assistance.

**Comment by caseyi** [comment]
I've changed the settings on some repos, and that will hopefully help
