### ISSUE TITLE
Add Order Input Screen

### ISSUE THREAD

**Issue by pragobur** [I-TECH-UW/OpenELIS-Global-2#220]
Add Order Input Screen 
https://192.168.12.151:8443/OpenELIS-Global/SamplePatientEntry.do

Add new patient details in same input screen Add Order; gives error upon **Save**; refer to screen shot.
![Error Upon save new Order](https://user-images.githubusercontent.com/79684973/109261929-1adb6200-781a-11eb-895b-12f68450be2d.jpg)

BUT If patient is added first under **Add/ Edit Patient**; Then proceed to Add Order, the record is Saved correctly.

Kindly look into the issue add Order input screen.

**Comment by caseyi** [comment]
Thank you, we were able to resolve that issue.
