### ISSUE TITLE
Cannot add a new test; error upon save.

### ISSUE THREAD

**Issue by pragobur** [I-TECH-UW/OpenELIS-Global-2#222]
https://192.168.12.151:8443/OpenELIS-Global/TestAdd.do

**Admin > test management > test Organization > Add New Test**

https://user-images.githubusercontent.com/79684973/109292380-b634fd00-7843-11eb-8859-e22665a1be75.MOV

Error page upon saving:-

![UNABLE TO ADD TEST-Virology](https://user-images.githubusercontent.com/79684973/109292393-bc2ade00-7843-11eb-8176-32377a9560b7.jpg)

**Comment by caseyi** [comment]
Thank you, we have resolved this issue. Please let us know if it comes up again, but we believe the fix is permanent.
