### ISSUE TITLE
Search By Org Name not functioning

### ISSUE THREAD

**Issue by pragobur** [I-TECH-UW/OpenELIS-Global-2#223]
**Search By Org Name not functioning on Page:**

**Admin> Organization**
https://192.168.12.151:8443/OpenELIS-Global/OrganizationMenu.do

Click on search button; no data is displayed on grid

https://192.168.12.151:8443/OpenELIS-Global/SearchOrganizationMenu.do?search=Y&startingRecNo=1&searchString=molecular
![Search By Org Name not functioning](https://user-images.githubusercontent.com/79684973/109293662-87b82180-7845-11eb-9764-6221b93b67c4.png)

**Comment by caseyi** [comment]
Thank you, we will address this.

**Comment by caseyi** [comment]
We have just finished some bug fixes, which include fixes for this.
