### ISSUE TITLE
assigning tests to panel

### ISSUE THREAD

**Issue by ubheeram** [I-TECH-UW/OpenELIS-Global-2#228]
![assign test to panels to make active](https://user-images.githubusercontent.com/79691338/109841604-10e0a700-7bfe-11eb-9424-20539930bf1c.png

how can already existing tests be assigned to a panel.
how can panels be edited, modified or deleted

**Comment by caseyi** [comment]
Hello,

Under manage panels - test assignment, one selects the panel, then assigns tests to it. If a panel no longer has any tests assigned, it will no longer appear (thus removing it). Panels can be renamed in the manage tests - rename panel feature, though we should include it in the list. 

I hope this answered your questions. Please let me know if there is anything I can elaborate on!
