### ISSUE TITLE
Cannot view test Catalogue

### ISSUE THREAD

**Issue by pragobur** [I-TECH-UW/OpenELIS-Global-2#231]
https://192.168.12.151:8443/OpenELIS-Global/TestCatalog.do?

Go To Admin 
Under Test Organization --> View Test Catalog
![CannotViewtest Catalog](https://user-images.githubusercontent.com/79684973/109955558-0dcbe080-7cfc-11eb-9dd8-2c8125389228.jpg)

**Comment by caseyi** [comment]
We fixed the data issue in the DB
