### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by medicopedia** [I-TECH-UW/OpenELIS-Global-2#258]
ERR_TOO_MANY_REDIRECTS !!!

**Comment by caseyi** [comment]
Thanks! That was indeed an issue for quite some time. The newest installer should have this fixed: https://www.dropbox.com/s/csh2usuv10tylx4/OpenELIS-Global_2.3.3.18_Installer.tar.gz?dl=0
