### ISSUE TITLE
Add missing translation in the new React  FrontEnd

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#585]
You need to replace hardcoded labels with translations using react-intl
With in an Element Context do 
 ```
const intl = useIntl();
 {intl.formatMessage({ id: "message.code" })}
```
Outside an elemnt Context , do
` <FormattedMessage id="message.code" /> 
`
Before you add a new Message in the [message source files](https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/2.8/frontend/src/languages). , ensure the message doesn't exist already
 
An example in the [CreatePatient](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/2.8/frontend/src/components/patient/CreatePatientForm.js) component, most of the field labels are hard coded. ie. ["Unique Health ID number" ](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/2.8/frontend/src/components/patient/CreatePatientForm.js#L305)

Another component where translations are needed is the [Search Patient Form](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/2.8/frontend/src/components/patient/SearchPatientForm.js)

The above is just an example and you can look through other components.

**Comment by jona42-ui** [comment]
hello,
can you assign me this, please?

**Comment by mozzy11** [comment]
Thanks @jona42-ui

**Comment by jona42-ui** [comment]
Hi @mozzy11 
I want to test the front end locally  in dev
Any straight forward way or I need to use docker.

**Comment by mozzy11** [comment]
A docker spin up would be more straight forward.
https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/2.8#building-the-docker-images-from-source-code

**Comment by jona42-ui** [comment]
Does it take conssiderably so long from your side?
especial on ;
`docker-compose -f build.docker-compose.yml up -d --build`

**Comment by mozzy11** [comment]
yeah definately it depends on your internet speed , but also its because docker is building a lot of stuff from scratch

**Comment by mozzy11** [comment]
For faster Testing in the dev enviroment , run tthe frontend app and OpenELIS backend natively on the machine and the other services in docker

**Comment by mozzy11** [comment]
I updated the [instructions](https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/2.8#running-published-docker-images-with-locally-compiled-artifacts-ie-the-war-file-and-local-frontend-source-files) to have a quicker way of running locally built artifacts with docker.

You don't have to run   `docker-compose -f build.docker-compose.yml up -d --build`. as it will do a fresh docker build on your local machine which often take longer and more resources. 

Just do a maven build for the project and as long as you have a compiled war file. , 
run   `docker-compose -f dev.docker-compose.yml up -d     `. to just deploy the compiled artifacts in existing docker images.


Ensure to first pull the changes I've just pushed

**Comment by jona42-ui** [comment]
on it!

**Comment by jona42-ui** [comment]
hello Mozzy
Started the containers succesfully
but unable to access it at `http://localhost:8080`

**Comment by jona42-ui** [comment]
hello Mozzy 
am not sure if my browsers have a problem, have tried chrome, firefox(default) and brave


![Image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/78595738/759b30d3-c986-4301-aaa3-32f040f6d45a)

trying to look at logs by `sudo docker-compose -f dev.docker-compose.yml logs frontend.openelis.org
`
gives 


![Image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/78595738/f091e738-7b42-4081-bf82-bfb55183107b)

but still accessing the instance gives;



![Image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/78595738/9a4e7c7e-60ce-4a22-a38a-ad93805f2150)

**Comment by jona42-ui** [comment]
even that on the readme
`https://localhost/ fails`

**Comment by jona42-ui** [comment]
anything am missing??

**Comment by mozzy11** [comment]
@jona42-ui , the app is running on https and using self assigned certs. so definitely it shows that warning. 
Click advanced and the Click accept

**Comment by alishad846** [comment]
Good Evening Sir,
can u assign me this issue..
Thanks

**Comment by jona42-ui** [comment]
[Screencast from 11-13-2023 05:11:37 PM.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/78595738/257f468e-db9b-4177-bbe7-707b76d13823)


did some work on the createpatientform
Does it look like something you anticipate??
will be sharing the PR
@mozzy11

**Comment by mozzy11** [comment]
@alishad846 this issue is already assigned to @jona42-ui .
can you take a look at this https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/592

**Comment by mozzy11** [comment]
Thanks @jona42-ui for attempting to work the issue. 
Can you click the User avatar icon in the right hand corner and switch the Locales to ensure your new translations work ??

**Comment by jona42-ui** [comment]
[Screencast from 11-13-2023 10:14:32 PM.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/78595738/3b4dfe87-1667-4d0f-a30e-693176db3128)

**Comment by jona42-ui** [comment]
@mozzy11 can you please look at this
https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/593

**Comment by jona42-ui** [comment]
i can see there are still more components!
on my radar!

**Comment by jona42-ui** [comment]
Pr here
https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/611/

**Comment by jona42-ui** [comment]
@mozzy11  am getting this on;
![Screenshot from 2023-12-07 20-03-19](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/78595738/2e3d7e86-15bd-4ed9-bb2e-f734378a781e)
Dependencies look intact , is there anything to be done
