### ISSUE TITLE
Add UI-validation to the new Add order page in the new Front end

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#592]
The new Add Order Form can be submitted when some Mandatory values are missing . This leads to failure because of the backend validation.

Madatory fields are 
#####  Add Patient Page
- Patient National Id
- Patient Birth Date
- Patient Gender

#####  Add Sample Page
- Atleast one sample

##### Add Order Page
- Lab  Number
- SIte Name 
- Requester's Last Name: 
- Requester's First Name: 

Steps to Reproduce
1. When you go to Add order   https://openelis28.openelis-global.org/AddOrder
2 Click `Next` until you find Submit
3. Click `Submit`.The form will submit but shows a Failre Notification

The Form shouldn't be submitted if any of the above fields is missing. 

To reproduce localy see   https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/2.8#running-docker-containers-with-locally-compiled-artifacts-ie-the-war-file-and-local-frontend-source-files

**Comment by WodPachua** [comment]
Hai, could I be assigned to work on this? @mozzy11

**Comment by jona42-ui** [comment]
hi @mozzy11  do we have any library we use.
do you have an example where you have done validation such that I look at the standard and consistency?

**Comment by mozzy11** [comment]
This is partially done  [here](https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/645)

**Comment by jona42-ui** [comment]
This is what I see on attempt to submit(actually after submitting)
![Screenshot from 2023-12-12 17-28-45](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/78595738/5ae3fe5d-001c-4dde-9992-fa1dfcc89c19)

so I suggest the design consideration to be;

1. highlight the mandatory fields with an asterisks
2. if not field, error message next to the field and not allowing continuation
3. disable submit button untill manadtory fields are filled

@mozzy11  what do you think of this.(just to get me on the right path)

**Comment by mozzy11** [comment]
Yeah , i updated that.

**Comment by Keshav-0907** [comment]
Hi @mozzy11 , I was trying to setup [This OpenELIS Repo](https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/2.8 but got this `Not Authenticated`. Can you please assist me, how to get it authenticated and eventually start contributing 

![Image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/91189139/7d26a3bd-fe91-41a3-b665-845cac066b7e)

**Comment by mozzy11** [comment]
hello @Keshav-0907 , you're trying to access the app directly on port 3000. its supposed to be accessed through the proxy on port 443 see https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/2.8?tab=readme-ov-file#the-instaces-can-be-accesed-at
