### ISSUE TITLE
Complete the Home DashBoard

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#594]
The current home dashboard on OpenELIS 3.x (branch 2.8) only displays  cards with the Dashboard counts.
see https://openelis28.openelis-global.org/
Complete the dashboard so that the cards are clickable and can display the actual corresponding list of orders

see the Requirements document. https://docs.google.com/document/d/1bH1eGBnn700OGshG-kIFInHPKz0c8XEK

For testing local changes . see. https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/2.8#running-docker-containers-with-locally-compiled-artifacts-ie-the-war-file-and-local-frontend-source-files

**Comment by charu1603** [comment]
Hey @mozzy11,I am chaitrali kakde , a 3rd year CS student and I'm eager to participate in GSoC this year and contribute to this issue. However, I'm currently facing a login access problem.
Could you please guide how to obtain the necessary credentials or permissions to access the development environment and address this issue?

![Image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/96014425/84422a2c-eb1b-4d65-b18b-0fb2d75d648a)

**Comment by Agaba-derrick** [comment]
hey @mozzy11 can you please assign to me this issue

**Comment by Agaba-derrick** [comment]
Unfortunately i am finding it hard to know the destination of the clickable cards 
Ie, Which API should i call on;
- Orders Entered By User
- Orders Rejected
- Incoming Orders

**Comment by Agaba-derrick** [comment]
I would also like to know where the Repo for the new front end located  ?

**Comment by mozzy11** [comment]
hello @Agaba-derrick , the new UI is still hosed on branch [2.8](https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/2.8) .

We don't have a Rest endpoint yet for the above . 
Am going to create one endpoint as an example for one of the List and you can create the rest

**Comment by Agaba-derrick** [comment]
Thank you for the update, I will work on  creating the remaining Rest endpoints, if there are also other specific requirements and details, i request to be filled in.

**Comment by tendomart** [comment]
@Agaba-derrick  there is a PR here https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/660 you can fetch changes just in case

cc @mozzy11

**Comment by Agaba-derrick** [comment]
Thank you for the update, I will work on  creating the remaining Rest endpoints, if there are also other specific requirements and details, i request to be filled in.

> @Agaba-derrick there is a PR here #660 you can fetch changes just in case
> 
> cc @mozzy11

thanks @tendomart

**Comment by mozzy11** [comment]
@tendomart @Agaba-derrick , 
Ive done more work on this issue https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/666

@tendomart i realised the Expandanble tiles wouldnt still do for us want we want  based on the requirements. 
I just played with the Clicackable tiles to switch between the DashBoard Summary and the Detailed view of the Metrics

**Comment by mozzy11** [comment]
@Agaba-derrick you can continuew more work here ie adding the Lab section (tabs) filters on the Detailed view Page

**Comment by tendomart** [comment]
@mozzy11  so you imply swithching back to Clickable Tiles is the way to go.?

or we delve into a different option still

**Comment by mozzy11** [comment]
@tendomart i dont see any default component that can  switch between a tile and a Full Page view. 
The Expandable tile only switches between a tile and a limited expanded view. 

From the Requirements doc, on clicking the tile, it should expand into a full-page View  . 

is there any component that can  switch between a Tile and Full page view on the Same Page ??

**Comment by tendomart** [comment]
Hey @mozzy11  have you experienced failure to start the "itechuw/certgen:main" container ?

it's been in "restarting mode" with status 0 even after deleting the image and creating a new one.

I experinced this after pulling in the latest changes.

**Comment by mozzy11** [comment]
@rahul6603 can you also pull the latest images especially for frontend

**Comment by rahul6603** [comment]
After pulling the latest changes, doing clean install and restarting everything, it works. Thanks @mozzy11 !

**Comment by Agaba-derrick** [comment]
> @Agaba-derrick you can continue more work here ie adding the Lab section (tabs) filters on the Detailed view Page

![Screenshot from 2024-01-12 05-04-47](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/79217378/9ca87350-c4a2-493c-bc10-04e125e6443e)
hey  @mozzy11 by adding the lab section filters on the detailed view page do you mean I add a Nav button to the Nav bar shown in the screenshot below?
@tendomart

**Comment by mozzy11** [comment]
@Agaba-derrick , 
Can you take a look at the Home Dashborad cards here https://openelis28.openelis-global.org/ .
Also Ensure to take a look at the requirements doc. https://docs.google.com/document/d/1bH1eGBnn700OGshG-kIFInHPKz0c8XEK

**Comment by Agaba-derrick** [comment]
> @Agaba-derrick , 
> Can you take a look at the Home Dashborad cards here https://openelis28.openelis-global.org/ .
> Also Ensure to take a look at the requirements doc. https://docs.google.com/document/d/1bH1eGBnn700OGshG-kIFInHPKz0c8XEK
> 

@mozzy11 noted,am also still working on my other pr although my server is still Broken with an authentication problem ....

**Comment by rahul6603** [comment]
Hey @mozzy11 I have read the requirements doc and would like to contribute on this issue. I will start by adding tabs for lab sections.

**Comment by Agaba-derrick** [comment]
@rahul6603 kindly there is a PR in draft that was put 24hrs ago .

**Comment by josephbate** [comment]
hello @mozzy11 i want to try out this issue how can assign myself to this ticket

**Comment by Agaba-derrick** [comment]
@josephbate there is #693 work in progress for this !

**Comment by tendomart** [comment]
@mozzy11  was this completed according to requirements?

**Comment by mozzy11** [comment]
its not yet complete , but the remaining work is not so propriety as the other issues. 
Ideally Having breadcrups on all the pages is high priority

**Comment by tendomart** [comment]
Okk.

**Comment by manzil-infinity180** [comment]
@mozzy11 assign to me i want to work on it

**Comment by SanjayRam07** [comment]
@mozzy11 Is this issue still available.
Can I work on this issue?
