### ISSUE TITLE
Results component should support  search Params via the URL

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#612]
The Results component only supports search parameters via the form input . see https://openelis28.openelis-global.org/result?type=unit&doRange=false
It should also also support the following search params passed via the URL for the corresponding pages 
ie
 Results -> 
- By Unit.  : testSectionId=`<TestSectionId>`
- By Patient. : patientID=<`PatientID>`
- By Order : accessionNumber=`<accesionNumber>`.  (already implemented)
- By Range or Oder Numbers : accessionNumber=`<accesionNumber>`
- By Test Date : collectionDate=`<date>`&recievedDate=`<date>`&selectedTest=`<TestId>`&selectedAnalysisStatus=`<StatusId>`&selectedSampleStatus=`<SampleStatusId>`

see [Example](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/2.8/frontend/src/components/resultPage/SearchResultForm.js#L183-L195) supporting accession number via the URL for  Results  > By Order
ie. https://openelis28.openelis-global.org/result?type=order&doRange=false&accessionNumber=DEV01230000000000005

For testing local changes . see. https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/2.8#running-docker-containers-with-locally-compiled-artifacts-ie-the-war-file-and-local-frontend-source-files

**Comment by rahul6603** [comment]
Hi @mozzy11 ! I have created a PR for this issue - https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/665
