### ISSUE TITLE
Validation component should support search Params via the URL

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#613]
The Validation component only supports search parameters via the form input . see  https://openelis28.openelis-global.org/validation?type=routine
It should also also support the following search params passed via the URL for the corresponding pages 
ie
 Validation -> 
- Routine.  :  testSectionId=`<TestSectionId>`
- Search By Order. :   accessionNumber=`<accesionNumber>`.
- Search By Test Date :   date=`<date>`
- Search By Range Of Orders :   accessionNumber=`<accesionNumber>`.

see [Example](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/2.8/frontend/src/components/resultPage/SearchResultForm.js#L183-L195) supporting accession number via the URL for  Results  > By Order
ie. https://openelis28.openelis-global.org/result?type=order&doRange=false&accessionNumber=DEV01230000000000005

For testing local changes . see. https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/2.8#running-docker-containers-with-locally-compiled-artifacts-ie-the-war-file-and-local-frontend-source-files

**Comment by rahul6603** [comment]
Hi @mozzy11 thanks for looking at other PRs! I had raised a PR for this one as well - https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/656
