### ISSUE TITLE
WorkPlan component should support search Params via the URL

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#614]
The WorkPlan component only supports search parameters via the form input . see   https://openelis28.openelis-global.org/WorkPlanByTestSection
It should also also support the following search params passed via the URL for the corresponding pages 
ie
 WorkPlan -> 
- By Test Type : testId=`<TestId>`
- By Panel Type : panelId=`<PanelId>`
- By Unit:  testSectionId=`<TestSectionId>`
- By Priority:  priority=`<Priority>`

see [Example](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/2.8/frontend/src/components/resultPage/SearchResultForm.js#L183-L195) supporting accession number via the URL for  Results  > By Order
ie. https://openelis28.openelis-global.org/result?type=order&doRange=false&accessionNumber=DEV01230000000000005

For testing local changes . see. https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/2.8#running-docker-containers-with-locally-compiled-artifacts-ie-the-war-file-and-local-frontend-source-files

**Comment by rahul6603** [comment]
Hi @mozzy11 !
I am trying to build OpenELIS 2.8 - I am running on Mac OS - `docker-compose -f dev.docker-compose.yml up -d` however I get the following error - 
[
![Screenshot 2023-12-16 at 7 28 20 PM](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128216878/73813952-aef0-4b6f-9883-931390298409)
]
Are there any extra instructions to follow for Mac OS? I am looking forward to contribute to the project (starting with the open issues)!

**Comment by mozzy11** [comment]
hello @rahul6603 , 
yeah at the time we only publish linux based images ,

but you can add. `platform: linux/x86_64`
 on your services  for a quick fix 
see https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8

**Comment by rahul6603** [comment]
Thanks a lot @mozzy11 ! I am able to get my local setup working

**Comment by rahul6603** [comment]
Hi @mozzy11 ! I have created a PR for supporting this - https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/655 - Have attached testing results on the PR

**Comment by mozzy11** [comment]
Thanks @rahul6603
