### ISSUE TITLE
Add the right hierarchy of Breadcrumbs to pages

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#652]
Most of the 0e3 pages miss BreadCrumps to link back to the previous parent page . 
Add the right hierarchy of Breadcrumps to all the pages ,with the default linking back to the home page .
Example Pages where we have Breadcrumps is the Patient History page with [breadcrumbs](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/2.8/frontend/src/components/patient/resultsViewer/results-viewer.tsx#L101-L112) linking back to the parent Search Patient page and Home Page 

see https://oe3.openelis-global.org/PatientResults/2

For testing local changes . see. https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/2.8#running-docker-containers-with-locally-compiled-artifacts-ie-the-war-file-and-local-frontend-source-files

**Comment by Agaba-derrick** [comment]
hey @mozzy11 please kindly assign me this issue

**Comment by rahul6603** [comment]
Hey @mozzy11 , I would also like to help on this issue. Can you please tell in which places do you want breadcrumbs to be added?

**Comment by mozzy11** [comment]
Definitely the any page where we don't have them

**Comment by mozzy11** [comment]
hello @rahul6603 , do you have any problems with this issue , I think its  pretty more straight forward

**Comment by rahul6603** [comment]
Hey @mozzy11 , I have found pages where breadcrumbs are missing, and have started working on it.

**Comment by mozzy11** [comment]
hello @Agaba-derrick  ,are you working on this ??
@rahul6603 can take it on and get it completed

**Comment by Agaba-derrick** [comment]
@mozzy11 noted

**Comment by tendomart** [comment]
Is anoyone still working on this ticket?

**Comment by Agaba-derrick** [comment]
@rahul6603

**Comment by rahul6603** [comment]
Hi @tendomart I have created couple of PRs - https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/684 and https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/685 for this issue, do you want me to continue working on it?

**Comment by tendomart** [comment]
No it's okk. @rahul6603  I think will just drop in a few PR's too..

noticing a couple of pages still lack breadcrumbs

**Comment by rahul6603** [comment]
Thanks @tendomart !

**Comment by mozzy11** [comment]
@tendomart , @rahul6603 @Agaba-derrick <
Who is currently working on this issue ??

**Comment by Agaba-derrick** [comment]
@mozzy11 I'm working on it

**Comment by mozzy11** [comment]
Alright , can you create a single PR and ad the breadcrumbs to all the Pages missing them??
Please don't forget to translate you labels . see my comment here https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/683#discussion_r1452436133

**Comment by mozzy11** [comment]
Were you able to solve the issues in your dev environment>>

**Comment by sherrif10** [comment]
hello @Agaba-derrick . Any progress.

**Comment by Agaba-derrick** [comment]
@sherrif10 yes I should be able to put this up for review soon !!

**Comment by mozzy11** [comment]
@tendomart @Agaba-derrick , 
If you feel you dont have enough time , we can make it open for others to pick it up

**Comment by tendomart** [comment]
Am yet to continue on the weekend to look the comments you raised, though truthfully speaking time has not been enough my sidde.

**Comment by devshah7774** [comment]
@mozzy11 , if this issue is available, can I work upon it?

**Comment by mozzy11** [comment]
i have seen @konavivekramakrishna  has made a more clear PR  https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/737 for this issues

**Comment by tendomart** [comment]
Alright.  If it fills in the missing gaps and satisifies the demands..we can fetch those in.

**Comment by mozzy11** [comment]
Thanks @konavivekramakrishna for working on this issues
