### ISSUE TITLE
Add DatePicker to `Results > By Test Date` page

### ISSUE THREAD

**Issue by rahul6603** [I-TECH-UW/OpenELIS-Global-2#654]
Use DatePicker instead of TextInput in `Results > By Test Date` page - 
- consistency for date input across project (e.g. DatePicker is used in `Patient > Add/Modify Patient` page)
- easier for users to input date
- doesn't allow user to input any random text

**Comment by rahul6603** [comment]
Hi @mozzy11 , I have created a PR to make this small enhancement - https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/653/ ! Could you please review it, thanks!

**Comment by rahul6603** [comment]
![Uploading Screenshot 2023-12-20 at 3.10.37 PM.png…]()

**Comment by mozzy11** [comment]
Thanks @rahul6603 . let me look at the PR
