### ISSUE TITLE
Add API pagination to Patient Search Results

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#680]
When searching Patients  , theres [UI pagination](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/2.8/frontend/src/components/patient/SearchPatientForm.js#L340-L346)  to limit the number results displayed in the UI.
We should also implement  API pagination to limit the number of results being returned by the [API ](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/2.8/src/main/java/org/openelisglobal/common/rest/provider/PatientSearchRestController.java#L49)in a single call.
This commit https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/619/commits/c4051375c9d63632f0fca5fc908321e828f95990 can provide an insight on how pagination has been previously done on workplan search results.

The first step would be to create a new patient  paging property ie `org.openelisglobal.paging.patients.pageSize:99` in the [PagingProperties](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/src/main/java/org/openelisglobal/common/paging/PagingProperties.java#L7) 

For testing local changes . see. https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/2.8#running-docker-containers-with-locally-compiled-artifacts-ie-the-war-file-and-local-frontend-source-files

**Comment by rahul6603** [comment]
Hi @mozzy11 , I would like to work on this issue. Please assign it to me.

**Comment by rahul6603** [comment]
Hi @Agaba-derrick I am already halfway through the changes required for this issue and will make a PR soon, do you mind looking at the other issue similar to this one - https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/681  :)
cc : @mozzy11

**Comment by Agaba-derrick** [comment]
> Hi @Agaba-derrick I am already halfway through the changes required for this issue and will make a PR soon, do you mind looking at the other issue similar to this one - #681 :) cc : @mozzy11

hey @rahul6603 you can surely proceed with changes here, i will proceed with  #681

**Comment by rahul6603** [comment]
Great, thanks @Agaba-derrick !

**Comment by mozzy11** [comment]
@rahul6603 any progress on this ??

**Comment by rahul6603** [comment]
Hi @mozzy11 , I have worked on this issue in the merged PR - https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/690

**Comment by mozzy11** [comment]
oh Thanks . sorry
