### ISSUE TITLE
Add API pagination to the Dashboard Order Lists

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#681]
When displaying Order Lists on the Home Darshboard  , theres [UI pagination](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/2.8/frontend/src/components/home/Dashboard.tsx#L456-L462)  to limit the number results displayed in the UI.
We should also implement  API pagination to limit the number of results being returned by the [API ](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/2.8/src/main/java/org/openelisglobal/common/rest/provider/PatientDashBoardProvider.java#L364)in a single call.
This commit https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/619/commits/c4051375c9d63632f0fca5fc908321e828f95990 can provide insight on how pagination has been previously done on workplan search results.

Use the  [results paging property](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/src/main/java/org/openelisglobal/common/paging/PagingProperties.java#L9) ie `org.openelisglobal.paging.results.pageSize:99` in the [PagingProperties](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop/src/main/java/org/openelisglobal/common/paging/PagingProperties.java#L7) 

For testing local changes. see. https://github.com/I-TECH-UW/OpenELIS-Global-2/tree/2.8#running-docker-containers-with-locally-compiled-artifacts-ie-the-war-file-and-local-frontend-source-files

**Comment by bilalshaikh292** [comment]
heyy @mozzy11 I would like to give this a try ?

**Comment by mozzy11** [comment]
great , let me assign it to you

**Comment by bilalshaikh292** [comment]
thanks @mozzy11 I currenty started working It will take me some time as i Have experiance of working in differnt techstack. if i face any issue i will ping you .

**Comment by bilalshaikh292** [comment]
and also @mozzy11 is there any issue related to frontend ,issue related to JavaScript , React or TypeScript as I am very much familer with that technology.

**Comment by mozzy11** [comment]
Since the Backend API is  Java-Spring based , and the Front end is React based , most issues would engage both Java and React. 
Can you first contribute to this too https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/652

**Comment by bilalshaikh292** [comment]
ok @mozzy11 but #652 is already being assigned . I think i should start with this one ?

**Comment by ArbajAnsari19** [comment]
If no one is working please assign this to me.

**Comment by mozzy11** [comment]
Any progress on this ??

**Comment by mozzy11** [comment]
@bilalshaikh292 , are you still working on this issue ??

**Comment by ahmedasad236** [comment]
Hi @mozzy11 

I have worked on same feature in different projects. I suggest to implement this feature using [https://tanstack.com/query/v3/](React-Query) for several features:

- Ease to implement pagination
- Cashing
- Also, support infinite pagination

Can you assign me for this feature ?

**Comment by SomayajuluSharma** [comment]
Hello, @mozzy11 is anyone working on this?

**Comment by parthnagdev** [comment]
> Hello, [@mozzy11](https://github.com/mozzy11) is anyone working on this?

hey @SomayajuluSharma yes i am working and its almost complete

**Comment by mozzy11** [comment]
Hello @parthnagdev , 
any progress here ??

**Comment by parthnagdev** [comment]
> Hello [@parthnagdev](https://github.com/parthnagdev) , any progress here ??

Yep, all done! just running tests and cleaning up the code. Will make a PR soon.
