### ISSUE TITLE
Support UI  based configuration properties

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#699]
Currently Our Configuration properties are loaded from a [properties files](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop_3x/src/main/resources/application.properties) .
Add support for the new  UI to be able to override the Configs with, the default values being loaded form the properties files

For testing local changes. see. https://github.com/I-TECH-UW/OpenELIS-Global-2?tab=readme-ov-file#running-docker-containers-with-locally-compiled-artifacts-ie-the-war-file

**Comment by josephbate** [comment]
hello @mozzy11 
i am interested this ticket
can you please give more infoon this

**Comment by mozzy11** [comment]
can you handle one ticket at ago ??

**Comment by adityadeshlahre** [comment]
hey @mozzy11 
can please provide more information on this issue .

Thank You :smiley:

**Comment by Arnav2824** [comment]
hey @mozzy11 , I would like you to assign this issue to me

**Comment by mozzy11** [comment]
Many of our Configuration properties are loaded from the properties files on startup. 
We can add support to the new UI to be able to overide the default values in properties file via the UI

**Comment by SanjayRam07** [comment]
@mozzy11 Can I work on this issue?
Can you assign it to me?

**Comment by SanjayRam07** [comment]
@mozzy11 Is this issue still available?
Can I work on this issue?

**Comment by mozzy11** [comment]
Hello @SanjayRam07 , are you working on this issues?? 
Any progress ??

**Comment by mozzy11** [comment]
added comments
