### ISSUE TITLE
Re write the SampleBatchEntrySetup Page in React 

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#700]
Go to Order -> SampleBatchEntrySetup. 
This page need to be re-writen in React . 
This will also require creating a REST controller but keeping the same logic as the old [JSP controller](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop_3x/src/main/java/org/openelisglobal/samplebatchentry/controller/SampleBatchEntrySetupController.java)

For testing local changes. see. https://github.com/I-TECH-UW/OpenELIS-Global-2?tab=readme-ov-file#running-docker-containers-with-locally-compiled-artifacts-ie-the-war-file

**Comment by josephbate** [comment]
hello @mozzy11  
i am interested in this tickect 
can you assign me and if there is any more info please share

**Comment by sherrif10** [comment]
Hello @josephbate .Any progress.

**Comment by SanjayRam07** [comment]
Hello @mozzy11 @sherrif10 , is this issue still available?
Can I work on this issue?

**Comment by sherrif10** [comment]
Hello @josephbate , Any progress, incase the ticket is bit hard, feel free to pick a different ticket. Dont be stack on it for time.

**Comment by Abhiram0304** [comment]
Hello @mozzy11  @josephbate  is this ticket still open. Can i work on this?

**Comment by mozzy11** [comment]
@josephbate any progress on this ?? 
do you have any issue ??

**Comment by mozzy11** [comment]
This Issue is available for work

**Comment by manishjha-04** [comment]
Hey @mozzy11 I would like to work on this!

**Comment by mozzy11** [comment]
Thanks @manishjha-04 , i assigned you the issues

**Comment by manishjha-04** [comment]
Hey @mozzy11, can you tell me from where I can fetch  samples for viral load testing and  EID ? I've attached a picture for reference. Thanks!

![Screenshot 2024-03-23 175328](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/964b649d-738f-4f94-99a7-10821a19d658)

![Screenshot 2024-03-23 175304](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/10aa7134-c50b-47cb-85b4-4dc65eb36b85)

**Comment by mozzy11** [comment]
Thanks @manishjha-04 for working on this
