### ISSUE TITLE
Re write the PrintBarcode page in react 

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#701]
Go to Order -> PrintBarcode
This page need to be re-writen in React . 
This will also require creating a REST controller but keeping the same logic as the old [JSP controller](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop_3x/src/main/java/org/openelisglobal/barcode/controller/PrintBarcodeController.java)

For testing local changes. see. https://github.com/I-TECH-UW/OpenELIS-Global-2?tab=readme-ov-file#running-docker-containers-with-locally-compiled-artifacts-ie-the-war-file

**Comment by rahul6603** [comment]
Hey @mozzy11 can you please assign this issue to me? Thanks.

**Comment by SanjayRam07** [comment]
@mozzy11 Is this issue still available?
Can I work on this issue?

**Comment by rahul6603** [comment]
Hi @SanjayRam07 , I already have worked on this issue in this PR - https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/713
