### ISSUE TITLE
Rewrite Patient Status Report report screen in the new React Framework

### ISSUE THREAD

**Issue by caseyi** [I-TECH-UW/OpenELIS-Global-2#705]
https://www.pivotaltracker.com/story/show/185355225

Here is the link, but it's essentially just rewriting this page from the old UI into the new react and carbon UI. 

https://oe3.openelis-global.org/api/OpenELIS-Global/Report?type=patient&report=patientCILNSP_vreduit

**Comment by adityadeshlahre** [comment]
![lookDiff](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/132184385/19f07d0a-6a35-4f8f-beb0-092a0f104347)

will raise the Draft PR soon :slightly_smiling_face:

**Comment by devshah7774** [comment]
Is this issue still open?
