### ISSUE TITLE
Numeric Result Fields should dynamically change color in the new UI

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#709]
in 2.7 when the result was out of the normal range the field would be highlighted in yellow, when outside the valid range it would be red (and would optionally put up an alert if the configuration was turned on), this validation didn't seem to make it to OpenELIS 3.

See results entry fields on the old UI https://oe3.openelis-global.org/result?type=patient&doRange=false

see results entry fields on 3.x  https://oe3.openelis-global.org/api/OpenELIS-Global/PatientResults?accessionNumber=&patientID=5

For testing local changes. see. https://github.com/I-TECH-UW/OpenELIS-Global-2?tab=readme-ov-file#running-docker-containers-with-locally-compiled-artifacts-ie-the-war-file

**Comment by Min2who** [comment]
can i get assigned with this?

**Comment by adityadeshlahre** [comment]
hey @Min2who 
any progress on this issue ?

**Comment by SanjayRam07** [comment]
@mozzy11 Can I work on this issue?
Is this still available?

**Comment by Abhiram0304** [comment]
Hello @mozzy11 , is this issue still available, can i contribute to the issue?

**Comment by adityadeshlahre** [comment]
![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/132184385/1b9f22da-695e-44a6-be35-3018645d6568)

hey @mozzy11 seem like this feature is already made it in branch develop_3x with proper notifications popups by @CalebSLane :slightly_smiling_face: and its working great. so this issue can be closed now

Thank You

**Comment by mozzy11** [comment]
Thanks @adityadeshlahre . Yeah its implemented
