### ISSUE TITLE
Fix Bar Code Generation in the New UI 

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#710]
When barcodes are printed, they don't corespond to the barcode configuration

When Barcode configuration is set to 2 for the order, and 1 for the sample (https://oe3.openelis-global.org/api/OpenELIS-Global/BarcodeConfiguration ) , but when I add an order, only one barcode label is generated.

**Comment by manishjha-04** [comment]
Hey @mozzy11 can you please assign me this issue?

**Comment by ArbajAnsari19** [comment]
hey @mozzy11, if no one is working on it, can you please assign this to me ?

**Comment by Abhiram0304** [comment]
Hello @mozzy11 is this issue still open, can i contribute to it?

**Comment by manishjha-04** [comment]
Hii @Abhiram0304  , @ArbajAnsari19  I have already worked on this issue and have raised the PR - #720

**Comment by manishjha-04** [comment]
Hey @mozzy11 the issue can be closed now ! since it has  been already fixed!
