### ISSUE TITLE
Suggestion of using tailwind instead of raw css and jsx component

### ISSUE THREAD

**Issue by utnim2** [I-TECH-UW/OpenELIS-Global-2#717]
Tailwind CSS offers a utility-first approach, streamlining your styling process by providing pre-defined classes for common styles. By leveraging Tailwind, you can write cleaner, more maintainable code without needing to manage complex CSS files. Integrating Tailwind into your project can improve development speed and consistency across components. Consider adopting Tailwind to simplify your styling workflow and enhance code readability

**Comment by varunsh17** [comment]
I agree as it will make the developement process consistent and easy to integrate with new technologies.

**Comment by mozzy11** [comment]
Thanks @utnim2 . 
We currently use [Carbon design system](https://carbondesignsystem.com/) for style guides .
And also our focus is on re-writitng component from the JSP to the react UI
