### ISSUE TITLE
Rewrite statistics Report (Aggregate Reports)  in the New React UI

### ISSUE THREAD

**Issue by manishjha-04** [I-TECH-UW/OpenELIS-Global-2#724]
Link : https://oe3.openelis-global.org/api/OpenELIS-Global/Report?type=indicator&report=statisticsReport
**Current Status:**
I am currently working on this task and will provide updates as progress is made.

**Comment by manishjha-04** [comment]
Hey @mozzy11 please review if its good to go so would be raising the pr 

https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/c2bab15c-d942-4848-98a1-05b5ac7df4ee

**Comment by manishjha-04** [comment]
Hii @mozzy11  ,I would be raising the PR by late evening! Just fixing some minor bugs

**Comment by sherrif10** [comment]
Hello @manishjha-04  , isnt this a duplicate issue  https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/741

**Comment by manishjha-04** [comment]
Hi @sherrif10, it isn't a duplicate issue. Here I've been focusing on aggregate reports within the routine section. As for issue #741, I'm currently improving the user interface for study reports.

**Comment by sherrif10** [comment]
Since all changes  part of reports still it can be handled in one PR. But for now its okay.

**Comment by mozzy11** [comment]
https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/740
