### ISSUE TITLE
Add run script for running or opening cypress/test

### ISSUE THREAD

**Issue by manzil-infinity180** [I-TECH-UW/OpenELIS-Global-2#727]
for simplication i just added two script in package.json for running or opening the cypress 

```
// frontend/package.json
    "cy:run": "cypress run --headless --browser chrome",
    "cy:open": "cypress open --browser chrome"
```

Desired/Expected Result
* by running the - **npm run cy:run** 
**--headless** Displays the browser instead of running headlessly [Link](https://docs.cypress.io/guides/guides/command-line#cypress-run-headed)

<img width="1299" alt="Screenshot 2024-02-26 at 9 24 56 PM" src="https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/119070053/853720ec-3db7-409e-b618-5c4fa9df1ecc">

* by running the **npm run cy:open**

The "browser" argument can be set to chrome, chromium, edge, electron, firefox to launch a browser detected on your system. Cypress will attempt to automatically find the installed browser for you. [(Link)](https://docs.cypress.io/guides/guides/command-line)

https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/119070053/edff35ce-25d5-4008-919b-19268037dab2

**Comment by manzil-infinity180** [comment]
hello sir  @mozzy11  review it please

**Comment by sherrif10** [comment]
Hopefully this needs to be closed.
