### ISSUE TITLE
Enhancement: Card elements are not aligned properly

### ISSUE THREAD

**Issue by pankaj-2503** [I-TECH-UW/OpenELIS-Global-2#731]
They should be aligned in single line with proper margin and spacing for better ui/ux.
![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/90036864/b7901c4b-e6b9-4ef2-8234-8509134eaa47)

**Comment by sherrif10** [comment]
To be more explicit, Make the title of this page to show that this work is basically for the website.

**Comment by Abhiram0304** [comment]
Hello!

Can I work on this Issue?
I can try solving this UI issue.

**Comment by sherrif10** [comment]
Hello @pankaj-2503 ,Are you interested in this work.

**Comment by pankaj-2503** [comment]
> Hello @pankaj-2503 ,Are you interested in this work.

yes , i would like to work on this issue

**Comment by sherrif10** [comment]
@Abhiram0304  since @pankaj-2503  is interested in working on this, you need to checkout open issues.

**Comment by Abhiram0304** [comment]
Ok @sherrif10

**Comment by mozzy11** [comment]
are talking abut the dashboard cards ??
