### ISSUE TITLE
 Select Component Lacks Placeholder Text for Guiding User Selection

### ISSUE THREAD

**Issue by PR4NJ41** [I-TECH-UW/OpenELIS-Global-2#738]
### Issue Description
In the Select component implementation, there is no placeholder text to guide the user to make a selection. This can lead to confusion or a less intuitive user experience, especially for new users unfamiliar with the expected actions.

### Expected Behaviour
The Select component should display a placeholder text that clearly instructs the user to "Select an option". This placeholder should be visible when no selection has been made, guiding users towards making their first selection.

### Steps to Reproduce
1.Navigate to the any page containing the Select component. For example- (https://localhost/WorkPlanByTest?type=test)
2.Observe the default state of the Select component before any interaction. Note the absence of clear, guiding placeholder text.

**Comment by mozzy11** [comment]
Thanks @PR4NJ41
