### ISSUE TITLE
Rewrite Study Reports in New React UI

### ISSUE THREAD

**Issue by manishjha-04** [I-TECH-UW/OpenELIS-Global-2#741]
**Current Status:**
I am currently working on this task and will provide updates as progress is made.

**Comment by mozzy11** [comment]
can you please specific a specific report you're working on ?? 
you need to do one report at a time for easy reviewing

**Comment by manishjha-04** [comment]
Hey @mozzy11 I was working on study reports as a whole as you can see that most of the pages follows a same format  only the title and print link gets changed ! 

So what i am doing is i am creating a generic component which could be reusable throughtout the study reports! Let me know your thoughts on this approach!

**Comment by mozzy11** [comment]
Thanks @manishjha-04 , that makes sense

**Comment by manishjha-04** [comment]
Hey @mozzy11   in the old ui what i found is the ward/dept/unit dropdown is not showing anything and  If I'm not mistaken, the dropdown for units should include options like biochemistry, hematology, and others, correct?  

If yes, so should i work on it? Or keep it as it is?

https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/cc9cc47c-707b-4f4a-9151-8c6c7a3084f1
