### ISSUE TITLE
 Fix Responsiveness of Modify Order Page

### ISSUE THREAD

**Issue by atulyadav745** [I-TECH-UW/OpenELIS-Global-2#747]
Issue Description:
The Modify Order page currently lacks responsiveness (on max-width <1056px), making it difficult for users to interact with the page across various devices and screen sizes. To enhance user experience and ensure usability, we need to address the responsiveness issues on this page.

To See issue visit: https://localhost/SampleEdit?type=readwrite
Current Behaviour
![befi](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/106299466/0430b1d8-ff6d-4e74-811b-13a883114afe)
Expected Behaviour
![After1](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/106299466/8db4ed47-4eaf-4d63-84f1-358414531b73)

**Comment by AyushMaurya001** [comment]
Hi @atulyadav745 I would like to work on this issue.
