### ISSUE TITLE
Recreating "ReferredOutTests" JSP component to New React Based UI

### ISSUE THREAD

**Issue by adityadeshlahre** [I-TECH-UW/OpenELIS-Global-2#753]
### [JSP Route Link](https://oe3.openelis-global.org/api/OpenELIS-Global/ReferredOutTests)

![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/132184385/a9320f4b-00c1-4d37-906c-5e5df560cee6)

### Route Button
![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/132184385/6d459257-8326-4290-bea2-ce4c64716eda)

currently am working on this !

Thank You :slightly_smiling_face:

**Comment by mozzy11** [comment]
hello @adityadeshlahre , 
any progress ??

**Comment by manishjha-04** [comment]
Hey @adityadeshlahre 
you can retrieve tests from the endpoint   `/rest/test-list `  and units from ` rest/user-test-sections `  !

**Comment by adityadeshlahre** [comment]
UI UPDATE : Implementation of multiple selection :slightly_smiling_face: 

![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/132184385/34b2c47f-80d5-4d4c-843b-852c258660c1)
