### ISSUE TITLE
Re-write Management Reports From JSP into React ui

### ISSUE THREAD

**Issue by sherrif10** [I-TECH-UW/OpenELIS-Global-2#754]
Am currently working on this  cc @mozzy11 Note that this will be handling different pages per pages since management reports were merged, so i will be including different pages that have been worked upon.

**Comment by mozzy11** [comment]
@sherrif10 can you please be specific about which exact report you're working on , please attach a link

**Comment by sherrif10** [comment]
Well i can start with this one since you have splitted them https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/758
