### ISSUE TITLE
Re-write Summary of All Tests Report (Aggregate Reports)  in the New React UI

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#755]
Re-write the above report in the new React UI
Link https://oe3.openelis-global.org/api/OpenELIS-Global/Report?type=indicator&report=indicatorHaitiLNSPAllTests

**Comment by manishjha-04** [comment]
Hey @mozzy11  I have already covered this in PR #740

**Comment by mozzy11** [comment]
Thanks @manishjha-04
