### ISSUE TITLE
Rewrite HIV Test Summary Report (Aggregate Reports) in the New React UI

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#756]
Link : https://oe3.openelis-global.org/api/OpenELIS-Global/Report?type=indicator&report=indicatorCDILNSPHIV
Re write the above Report in the new React UI

**Comment by manishjha-04** [comment]
Hey @mozzy11  I have already covered this issue in PR #740 , please review it!
