### ISSUE TITLE
Re-write Activity Report in the new React UI

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#758]
This should support generating the report the following Parameters ie 
By Test :https://oe3.openelis-global.org/api/OpenELIS-Global/Report?type=indicator&report=activityReportByTest
By Panel : https://oe3.openelis-global.org/api/OpenELIS-Global/Report?type=indicator&report=activityReportByPanel
By Test section : https://oe3.openelis-global.org/api/OpenELIS-Global/Report?type=indicator&report=activityReportByTestSection

**Comment by sherrif10** [comment]
Feel free to assign this one to me.

**Comment by Lovelyfin00** [comment]
Hi @sherrif10 
Are you still working on this?
If not, I would like to pick it up

**Comment by sherrif10** [comment]
Yes ,  Likely to push a PR this night.

**Comment by mozzy11** [comment]
@sherrif10 , still working on this ??

**Comment by mozzy11** [comment]
This issues is available for work

**Comment by mherman22** [comment]
assign me to it

**Comment by mozzy11** [comment]
Thanks @mherman22 , assigned

**Comment by sherrif10** [comment]
Comeon guys. i have a pending PR which needs to be attended. Am resolving the fix before lunch.Just bare with me by lunch.

**Comment by mherman22** [comment]
@mozzy11 i think i should let @sherrif10 finish this issue

**Comment by mozzy11** [comment]
Thats fine , but he has not been responding for a couple of days

**Comment by mozzy11** [comment]
@mherman22 can you look into https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/862

**Comment by mherman22** [comment]
yes @mozzy11 you can assign me to it

**Comment by sherrif10** [comment]
Current PR  https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/894
