### ISSUE TITLE
Re - Write AuditTrailReport In the new React UI 

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#761]
Link : https://oe3.openelis-global.org/api/OpenELIS-Global/AuditTrailReport

**Comment by manishjha-04** [comment]
Hii @mozzy11  can i work on this?

**Comment by devshah7774** [comment]
@mozzy11 , please assign me this issue..

**Comment by Lovelyfin00** [comment]
I'll start working on this since no one is working on it

**Comment by Lovelyfin00** [comment]
Working on this now

**Comment by mozzy11** [comment]
Thanks @Lovelyfin00 for doing the innitial work .

**Comment by mozzy11** [comment]
Ill close this and create a new Issue
