### ISSUE TITLE
Fix Responsiveness of Home page

### ISSUE THREAD

**Issue by PR4NJ41** [I-TECH-UW/OpenELIS-Global-2#763]
### Issue Description
Homepage Dashboard lacks responsiveness for max screen width < 425px
### Steps to Reproduce
Visit: https://localhost/
### Current Behaviour
![Screenshot from 2024-03-06 04-35-23](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/96368921/d24f6bc6-2584-45e9-95cd-90663e6100a6)

**Comment by nishant1194** [comment]
can I take up this issue

**Comment by PR4NJ41** [comment]
@nishant1194 This issue has already been resolved. So, I am closing this issue.

**Comment by PR4NJ41** [comment]
@nishant1194 This issue has already been resolved. So, I am closing this issue.
