### ISSUE TITLE
Average Turn Around Time returns NaN

### ISSUE THREAD

**Issue by Lovelyfin00** [I-TECH-UW/OpenELIS-Global-2#767]
1. Section: Dashboard -> Average Turn Around time

2. The Average Turn Around time container on the dashboard shows "NaN" instead of 0 if there's no value. The expanded view too shows NaN. The data being returned by the backend is 
`{receptionToResult: 'NaN', resultToValidation: 'NaN', receptionToValidation: 'NaN'}`

3. ### Supposed Fix

This can be fixed in two ways.

- Either it's fixed from backend by returning 0 or frontend uses conditional to render 0

4. Attach relevant screenshots and video recordings if necessary.
<br/>

![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/38161296/d8b8b07c-4de0-4e0e-9ac2-c06dbae72e20)

<br/>

![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/38161296/618f155a-6c96-40e1-99ee-cb0238cf5a75)

<br/>

5. Indicate the severity of the issue using the following ratings:
    1. This issue is something we would like to see improved in the future but does not significantly affect our work.

cc. @mozzy11 @CalebSLane

**Comment by mozzy11** [comment]
i would prefer a  backend fix
