### ISSUE TITLE
Local Code Setup issue

### ISSUE THREAD

**Issue by codewithunknown** [I-TECH-UW/OpenELIS-Global-2#782]
Issue:

before the my project in  docker was succesfully running and I can access the web application in localhost without any concern

I somehow removed all files in and wanted clone and setup again the project

until setup everything is working fine but 

frontend is working fine but the backend logs are 

```
2024-03-09 12:31:21 openelisglobal-webapp     | 2024-03-09T10:01:21.259+0300 -- INFO -- liquibase.lockservice Waiting for changelog lock....
2024-03-09 12:31:31 openelisglobal-webapp     | 2024-03-09T10:01:31.280+0300 -- INFO -- liquibase.lockservice Waiting for changelog lock....
2024-03-09 12:31:41 openelisglobal-webapp     | 2024-03-09T10:01:41.299+0300 -- INFO -- liquibase.lockservice Waiting for changelog lock....
```

the above continues I tried surfing the web but no use

can help is greatly appreciated 

ps : I can access the front end but the response is not coming from backend

@mozzy11 @rahul6603 @manishjha-04 @konavivekramakrishna @sherrif10 @atulyadav745

**Comment by adityadeshlahre** [comment]
Hey @codewithunknown 

make sure java 11 is installed and set it as default java version.

try these commands one by one 

`docker-compose -f dev.docker-compose.yml down -v`

`docker system prune --volume`

`docker-compose -f dev.docker-compose.yml up -d  --no-deps --force-recreate oe.openelis.org`

let me know if this works :slightly_smiling_face:

**Comment by adityadeshlahre** [comment]
> Hey @adityadeshlahre
> 
> ```
> unknown flag: --volume
> See 'docker system prune --help'.
> ```

ahh spelling mistake it was it should be 

`docker system prune --volumes`

**Comment by mherman22** [comment]
@codewithunknown if you checked the readMe file, there's this section -> https://github.com/I-TECH-UW/OpenELIS-Global-2?tab=readme-ov-file#running-docker-compose-with-locally-compiledbuilt-artifacts-ie-the-war-file-and-react-code-for-developers and it's what i personally followed to get me going.



> Hey @codewithunknown
> 
> make sure java 11 is installed and set it as default java version.
> 
> try these commands one by one
> 
> `docker-compose -f dev.docker-compose.yml down -v`
> 
> `docker system prune --volumes`
> 
> `docker-compose -f dev.docker-compose.yml up -d --no-deps --force-recreate oe.openelis.org`
> 
> let me know if this works 🙂

However, we can keep this in mind as it helps incase the steps in the link above are causing issues for some reasons.


> @adityadeshlahre
> 
> I would suggest please include that in readme so that if any new contributor faces trouble tell them to follow these
> 
> instead of surfing the internet they can get information quickly

What can be added maybe is that this repo's dev step is not like most outthere, here we really don't need an `npm start` command to start the app 😄 @mozzy11
