### ISSUE TITLE
Duplicate National IDs are persisted even after setting the 'duplicate national ID' property false 

### ISSUE THREAD

**Issue by common-cold** [I-TECH-UW/OpenELIS-Global-2#788]
Issue Description:

The Patient Configuration Menu has fields such as 
- Allow duplicate national ids 
- Allow duplicate subject number

Even after toggling their values to false, new patients can be persisted  with duplicate national IDs and subject Number. 
Currently there is no Validator present in the backend during the process of saving a new patient.

1. Patient Configuration Menu can be accessed by :

Admin -> Legacy Admin -> Patient Entry Configuration

Here the properties can be toggled to true or false.

Screenshots of the issue:

Duplicate National ID Property is set to false:

![Screenshot 2024-03-11 000026](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/71568044/8ed9e754-b610-434f-b77f-83fac28505c5)

Patients with duplicate national IDs are being persisted:

![Screenshot 2024-03-11 000217](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/71568044/7c1028c1-2d29-4831-bedd-b46ad30fdbf8)

**Comment by common-cold** [comment]
@mozzy11 can you assign this issue to me.

**Comment by codewithunknown** [comment]
@mozzy11 @common-cold 

just a heads up maybe, what I would say is there can be mutiple patients with same national ID

@mozzy11  I would suggest by default we can keep allowing mutiple patients with same national ID because say I am from `uganda` then there would be no point if only one patient from uganda can use our application

just reconsidering the edge cases

**Comment by common-cold** [comment]
@codewithunknown from what I could understand the national ID in the codebase refers to the unique identification no. given by the government to its citizen. In India we have Aadhaar Card as our National ID. I don't think the code base refers to the Country Code as national Id. Correct me if I'm wrong.

**Comment by mozzy11** [comment]
@common-cold any progress or blocker here ??

**Comment by mozzy11** [comment]
hello @common-cold any progress ??

**Comment by common-cold** [comment]
@mozzy11 yes i have done changes in the code-base I'll generate a PR soon.
