### ISSUE TITLE
Unable To perfrom Create Entries

### ISSUE THREAD

**Issue by codewithunknown** [I-TECH-UW/OpenELIS-Global-2#790]
I tried to increase the count In progress  and ready for validation by creating 

well though in https://oe3.openelis-global.org/ we can see the values

in my local machine I am unable to create the entries or records

to close this issue I would recommend attach a video where in local machine you can increase the count of the below mentioned fields

I am experiencing validation errors 

steps:
1.running my openELIS in local
2.attach a video where by you can perform create operation and can Increase the count of the below fields

![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/126901279/30a3b4d6-6cc5-4cfc-82f6-e376e90f8f4d)

**Comment by codewithunknown** [comment]
@mozzy11 

I think its an issue to consider as it effects our dev workflow

**Comment by codewithunknown** [comment]
![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/126901279/0e6b5c6d-7194-4032-b23e-99e688643ba2)


for reference

**Comment by manzil-infinity180** [comment]
I think you should join the forum and ask their instead of creating issue here the link - https://talk.openelis-global.org/invites/bUoK2R4fma

**Comment by mozzy11** [comment]
@codewithunknown can you start a Thread on [talk ](https://talk.openelis-global.org/)about the issues youre facing when trying to create an entry ?? you will get guidance . 
So am closing this because its not an issues
