### ISSUE TITLE
Re - Write the ARV Reports in the new React UI

### ISSUE THREAD

**Issue by sherrif10** [I-TECH-UW/OpenELIS-Global-2#797]
Link  https://localhost/StudyReports
https://localhost/api/OpenELIS-Global/Report?type=patient&report=patientARVInitial1

**Comment by manishjha-04** [comment]
Hello @sherrif10, I've already completed work on all the reports within the study reports. For most of them, I've already submitted the pull requests (PRs). For the remaining portion, the work is completed; only refactoring is required. I'll be submitting the PR for those by late evening.

Please refer issue #741

**Comment by sherrif10** [comment]
Ops my bad, can you go ahead and close those issues that you had worked on.
