### ISSUE TITLE
Re-Write PatientEID Reports into new React UI

### ISSUE THREAD

**Issue by sherrif10** [I-TECH-UW/OpenELIS-Global-2#798]
Link  https://localhost/api/OpenELIS-Global/Report?type=patient&report=patientEID1

**Comment by manishjha-04** [comment]
Hey @sherrif10, the pull request for this  has already been raised! Please check to see if the same issue still exists or not. I've already addressed it in my work.

Please refer to #741. All the reports within the study reports have already been covered , I have already worked on them!
