### ISSUE TITLE
Re-Write Double Form into New React Ui

### ISSUE THREAD

**Issue by sherrif10** [I-TECH-UW/OpenELIS-Global-2#807]
https://localhost/api/OpenELIS-Global/PatientEntryByProject?type=verify

**Comment by karthikrajpalavalasa** [comment]
@mozzy11 please assign this work to me!

**Comment by EdisonMeks** [comment]
@sherrif10 is this still available and ready for work

**Comment by sherrif10** [comment]
This was fixed.
