### ISSUE TITLE
Tablet mode: Inconsistent display  of  the input filed in modify order form 

### ISSUE THREAD

**Issue by jona42-ui** [I-TECH-UW/OpenELIS-Global-2#842]
# Description
The modifiy order form provides the first card with the Enter accession number field label, and a submit button.
When on tablet mode, the input field aligns to the right with the submit button on the left,on a portrait view port  which poses inconsistency and poor usability,

current look;

![Screen Shot 2024-03-20 at 12 40 48](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/78595738/26aadce3-b692-48c4-9144-4fdd5741ca53)

desktop
![Screen Shot 2024-03-20 at 12 46 39](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/78595738/b223c8c8-7101-476a-afd1-26ad93189a65)

To reproduce: get tablet viewports
     (portrait): 768 x 1024 pixels
     (landscape): 1024 x 768 pixels

**Comment by jona42-ui** [comment]
That's @atulyadav745  fine if you are able to reproduce it

**Comment by mozzy11** [comment]
Thanks @jona42-ui , 
Plaese you can test and let me know if the issues is fixed

**Comment by jona42-ui** [comment]
testing 1 2

**Comment by jona42-ui** [comment]
Resolved
