### ISSUE TITLE
Improve search by date input fields reponsiveness on small screens

### ISSUE THREAD

**Issue by jona42-ui** [I-TECH-UW/OpenELIS-Global-2#844]
In the order component, the search incoming test requests form provides fields for search by date.
The input field size remains constant across different screen sizes.
This renders it unresponsive and distorts the UI

current look
![Screen Shot 2024-03-20 at 14 15 23](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/78595738/142fad80-b0d3-4e59-b477-a31ffa25aed8)

Note: To see the Dev Console for a tablet, follow these instructions: https://developer.chrome.com/docs/devtools/remote-debugging/ 

or on the sizes;
    iPhone SE: 320 x 568 pixels
    iPhone 11 Pro: 375 x 812 pixels
    Google Pixel 2: 411 x 731 pixels

here: https://openelis28.openelis-global.org/ElectronicOrders

**Comment by Lovelyfin00** [comment]
Would like to work on this

**Comment by Lovelyfin00** [comment]
Hi @mozzy11 
This has been fixed.
In my previous responsivess [PR](https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/852/files), I noticed that [there's a class](https://github.com/Lovelyfin00/OpenELIS-Global-2/blob/34bceaec2a9d8b69cb5de04647c67ee0dee40963/frontend/src/components/Style.css#L493) for grid used across multiple pages. So I made it responsive on screen lesser than 792px.

This file for this issues uses the same [className which can be found here](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop_3x/frontend/src/components/eOrder/EOrderSearch.js#L110)

<br/>
<hr/>

![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/38161296/f0ed070f-4f59-42a0-bbd4-072806454df5)

**Comment by jona42-ui** [comment]
have you checked the screen sizes in the issue?

**Comment by jona42-ui** [comment]
if yes. share the screen shots please.

**Comment by Lovelyfin00** [comment]
@jona42-ui 

Iphone SE
<br/>

![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/38161296/6e0d3ec6-786e-4f6a-bebd-76ecd6435d3f)


<br/>
<br/>
<br/>
iphone 11 PRO
<br/>
<br/>

![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/38161296/2d59aedd-432b-4f1e-9838-8dbae7e86c36)
<br/>
<br/>

Google Pixel 2

<br/>
<br/>

![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/38161296/2b15160b-b238-4f44-a450-5c3710328358)

**Comment by Lovelyfin00** [comment]
@codewithunknown 
I used this chrome extension https://chrome.google.com/webstore/detail/simulateur-mobile/ckejmhbmlajgoklhgbapkiccekfoccmk?hl=en-US
