### ISSUE TITLE
Improve responsiveness of page work plan by test on small screens

### ISSUE THREAD

**Issue by 1SatyamJaiswal** [I-TECH-UW/OpenELIS-Global-2#848]
In the workplan tab, workplan by test page can be accessed where there is search field where the type of test is needed to be entered. The current tab becomes unresponsive for any smaller screen size. This distorts the UI and makes it unusable for the user. The error can be seen in the image attached.

Current -  
![Screenshot 2024-03-20 233933](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/76004625/6f2b0004-1f68-4c6e-b82c-a323d0fc33dc)

the error can be encountered on the page - [https://openelis28.openelis-global.org/WorkPlanByTest?type=test](url)
the UI breaks for screen sizes below - 1060px

**Comment by mozzy11** [comment]
@1SatyamJaiswal are you working on this issue ??

**Comment by 1SatyamJaiswal** [comment]
Yes I'm working on this issue please assign it to me

**Comment by mozzy11** [comment]
Thanks @1SatyamJaiswal
