### ISSUE TITLE
Improve responsiveness of programs page 

### ISSUE THREAD

**Issue by Lovelyfin00** [I-TECH-UW/OpenELIS-Global-2#851]
## Issue summary
The inputs in the programs page on the admin isn't responsive on smaller screen from 792px below.

## To Recreate
Go to the dashboard, click on the sidemenu and select admin. On the admin page, click on program entry. Reduce your device screen width to 792px and below.

## Screenshot

![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/38161296/ddf85549-f48e-4697-876b-aef294340c24)

**Comment by mozzy11** [comment]
Thanks @Lovelyfin00 for catching this

**Comment by Lovelyfin00** [comment]
> Thanks @Lovelyfin00 for catching this

Hi @mozzy11 
Thanks for your swift response 😄
