### ISSUE TITLE
Re- write the Dictionary Management Page in the new UI

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#862]
https://oe3.openelis-global.org/api/OpenELIS-Global/DictionaryMenu 

The functionality includes displaying , Editing and adding Dictionary elements

**Comment by mozzy11** [comment]
@mherman22

**Comment by mherman22** [comment]
assign me please!

**Comment by mherman22** [comment]
As you can see the status of the issue. Its in progress @adityadeshlahre

**Comment by adityadeshlahre** [comment]
alright @mherman22 :slightly_smiling_face:

**Comment by mozzy11** [comment]
Thanks @mherman22 for the innitila work . 
Remaining work includes

- Implementing API pagination on the UI side
- Implementing Modify Dictionary element

**Comment by mherman22** [comment]
> Thanks @mherman22 for the innitila work . Remaining work includes
> 
> * Implementing API pagination on the UI side
> * Implementing Modify Dictionary element

Exactly lemi start on it aswell
