### ISSUE TITLE
Re-Write printed Reports Configuration Menu to the new React UI

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#863]
https://oe3.openelis-global.org/api/OpenELIS-Global/PrintedReportsConfigurationMenu

**Comment by mherman22** [comment]
please @mozzy11 assign me to this instead!

**Comment by sayed4900** [comment]
@mozzy11 I want to work on this issue, can you assign it to me?

**Comment by mozzy11** [comment]
@sayed4900 any progress on this issue??

**Comment by mozzy11** [comment]
@manishjha-04 can you take this on ??
No response from @sayed4900

**Comment by manishjha-04** [comment]
Alright, @mozzy11, I'm working on it! Thank you!

**Comment by mozzy11** [comment]
Hello @manishjha-04 ,
Just write a Generic component for all the Configuration Pages , see issue  https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/1012

**Comment by sayed4900** [comment]
> @manishjha-04 can you take this on ?? No response from @sayed4900

I am sorry for my late. A month ago I told you that I would work on another issue and you moved it  to Todo to In Progress in Introductory Issues
