### ISSUE TITLE
Re- write Sample Configuration Menu page to the new React UI

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#864]
https://oe3.openelis-global.org/api/OpenELIS-Global/SampleEntryConfigMenu

**Comment by adityadeshlahre** [comment]
Hey @mozzy11 would like to work on this :slightly_smiling_face: !

**Comment by sayed4900** [comment]
@mozzy11 can you assign this issue to me?

**Comment by karthikrajpalavalasa** [comment]
@mozzy11  can you assign this issue to me?

**Comment by sayed4900** [comment]
@mozzy11 
I haven't started on that issue yet because I'm busy with do some integration testing, so If there someone else can work on it, please assign it to him.

**Comment by adityadeshlahre** [comment]
Hey @karthikrajpalavalasa am already working on this issue :slightly_smiling_face: !
You can find more issues in [here](https://github.com/I-TECH-UW/OpenELIS-Global-2/issues).

**Comment by karthikrajpalavalasa** [comment]
> Hey @karthikrajpalavalasa am already working on this issue 🙂 ! You can find more issues in [here](https://github.com/I-TECH-UW/OpenELIS-Global-2/issues).

ok

**Comment by mozzy11** [comment]
This issue depends on https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/1012
