### ISSUE TITLE
Add a code coverage Maven Plugin with the specified configuration.

### ISSUE THREAD

**Issue by Agaba-derrick** [I-TECH-UW/OpenELIS-Global-2#865]
1. **Affected Component:** Maven Configuration
2. **Steps to Reproduce:**
   - Open the `pom.xml` file in the project.
   - Navigate to the `<plugins>` section.
   - Add a code coverage Maven Plugin with the specified configuration.
   - Save the file.
   - run mvn clean install 
### Additional Details:
The addition of a code coverage Maven Plugin to the project's pom.xml file enhances the testing and quality assurance capabilities by enabling code coverage analysis during the testing process. This improvement supports better code quality assessment in integration testing.

**Comment by Agaba-derrick** [comment]
@mozzy11 @reagan-meant 
am working on this Issue

**Comment by bayehyg** [comment]
I had a go at it, can you check my work?
https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/941

**Comment by mozzy11** [comment]
@Agaba-derrick Are you still working in this ??

**Comment by Agaba-derrick** [comment]
@mozzy11  not really some one else can take over  this issue

**Comment by njiddasalifu** [comment]
Hi @Agaba-derrick  @mozzy11 if no one is working on this, I will like to take it up please. 
Feel free to assign me

**Comment by mozzy11** [comment]
Thanks @njiddasalifu

**Comment by josephbate** [comment]
hello  could i be assigned to this issue
