### ISSUE TITLE
GSOC project  Inquiry

### ISSUE THREAD

**Issue by codewithunknown** [I-TECH-UW/OpenELIS-Global-2#885]
Hello @mozzy11 

I'm working on the GSOC issue titled "Add support for user notification." The project description outlines the need to incorporate User Notifications into the new Front End, particularly for critical Orders and Results. Essentially, this involves developing a versatile Notification framework capable of accommodating various system notifications as required.

Now, I have a few questions regarding the project:

- Could you clarify what constitutes critical orders and how we can create them?
- When we mention results, which specific results are we referring to, and how can we generate them?
- Currently, the project seems to only utilize admin credentials (username: admin, password: adminADMIN!). Are there different user roles available? If so, could you provide details on these roles and how to create them?

Looking forward to your guidance on these matters.

**Comment by manishjha-04** [comment]
Hi @codewithunknown, for questions and issues like this, it's best to initiate a discussion thread on [OpenElis Talk](https://talk.openelis-global.org/). The GitHub issue section is primarily reserved for development-related matters. Thanks for your understanding

**Comment by mozzy11** [comment]
we can catchup on the community call on Thuusrday we go through the workflows with every one else
