### ISSUE TITLE
Re-write Export by Date Report in the new React UI 

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#895]
Go to Reports -> Study -> Export By Date 

- https://oe3.openelis-global.org/api/OpenELIS-Global/Report?type=patient&report=CIStudyExport
- https://oe3.openelis-global.org/api/OpenELIS-Global/Report?type=patient&report=Trends

**Comment by konavivekramakrishna** [comment]
@mozzy11 can you please assign me
