### ISSUE TITLE
Re-Write Non-conformity Notification in the Bew React UI

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#896]
https://oe3.openelis-global.org/api/OpenELIS-Global/Report?type=patient&report=retroCInonConformityNotification

Go to Reports -> Study ->  Non-conformity Notification

This Report needs to be re-written in the new Raect UI

**Comment by EdisonMeks** [comment]
@mozzy11 anyone working upon this?!

**Comment by mozzy11** [comment]
@EdisonMeks assigned ot to you

**Comment by mozzy11** [comment]
any one else can take on this issue. 
we need it as part of the relese

**Comment by rahul6603** [comment]
Hi @mozzy11 I can take up the issue. My university exams are over and I will soon make a PR for this.

**Comment by mozzy11** [comment]
Thanks @rahul6603 for working on this
