### ISSUE TITLE
Re -write Non Conform Section to the new React UI

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#897]
Go to the Main Menu - > Non Conform 
ie 
* https://oe3.openelis-global.org/api/OpenELIS-Global/ReportNonConformingEvent
*  https://oe3.openelis-global.org/api/OpenELIS-Global/ViewNonConformingEvent
*  https://oe3.openelis-global.org/api/OpenELIS-Global/NCECorrectiveAction

**Comment by YelyzavetaKo** [comment]
@mozzy11 
Hi, I would like to work on this issue if still available.

**Comment by karthikrajpalavalasa** [comment]
@mozzy11 can you assign this issue to me?

**Comment by konavivekramakrishna** [comment]
@mozzy11 

can you assign this to me, I have implemented the UI currently working POST requests

**Comment by konavivekramakrishna** [comment]
@mozzy11 

sorry for the delay. I'm encountering few blockers while dealing with `nceNumber`. I'll complete `viewNonConformingEvent` by today

**Comment by konavivekramakrishna** [comment]
- ![image](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/101407963/89c64b39-56da-4fe1-9249-980e8e5661a3)
- working on `viewNonConformingEvent` post request

cc : @mozzy11
