### ISSUE TITLE
Improve Responsiveness of Global Header on small screen devices

### ISSUE THREAD

**Issue by PR4NJ41** [I-TECH-UW/OpenELIS-Global-2#905]
## Description
Currently, the global header gets partially hidden on small screen sizes like screen width = 321px.

### Current Behvaiour
![7_b](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/96368921/55384d05-6782-4940-bb7d-e6654792ca5b)

## To Reproduce
1. Visit url = https://localhost/
2. Login

**Comment by mozzy11** [comment]
Thanks @PR4NJ41
