### ISSUE TITLE
Add Breadcrumbs to Bar Code page

### ISSUE THREAD

**Issue by PR4NJ41** [I-TECH-UW/OpenELIS-Global-2#907]
## Description
The Bar Code Page doesn't have Breadcrumbs.

### Current Behaviour
![8_b](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/96368921/ab96d550-ab83-467e-a224-d96fcc3d11d5)

## To Reproduce
Visit url = https://localhost/PrintBarcode

**Comment by mozzy11** [comment]
Thanks @PR4NJ41
