### ISSUE TITLE
Add tabs for test sections in Home Dashboard

### ISSUE THREAD

**Issue by rahul6603** [I-TECH-UW/OpenELIS-Global-2#931]
1. Note the section, tab, or page of OpenELIS that is affected by your issue.

    Home Dashboard

2. Describe in detail the steps you were followed to encounter the issue.

    As per to the [requirement document]( https://docs.google.com/document/d/1bH1eGBnn700OGshG-kIFInHPKz0c8XEK) for the Home Dashboard, we will use [Tabs](https://carbondesignsystem.com/components/tabs/usage/) to filter by test sections. This will be done for expanded tiles such as _In Progress_, _Ready for Validation_, etc.

3. Include the url where you encountered the bug.

    [Home Dashboard](https://openelis28.openelis-global.org/)

4. Attach relevant screenshots and video recordings if necessary.

![Screenshot 2024-03-29 at 1 51 39 AM](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128216878/d8b5a5ee-088a-4a9b-a224-e0a295761b61)

5. Indicate the severity of the issue using the following ratings:

    This issue is something we would like to see improved in the future but does not significantly affect our work.

**Comment by rahul6603** [comment]
Hi @mozzy11, this issue is an extension of the issue - https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/594. I have created a PR regarding the same - https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/932, can you please review it?
Thank you.

**Comment by mozzy11** [comment]
Thanks @rahul6603
