### ISSUE TITLE
Update  Gsoc.md 

### ISSUE THREAD

**Issue by Agaba-derrick** [I-TECH-UW/OpenELIS-Global-2#947]
# Update  Gsoc.md  to the current dates of Gsoc 

1. Navigate to the [docs](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/develop_3x/docs/gsoc.md) and update the docs to the current  dates of Gsoc

**Comment by SubratYeeshu** [comment]
Hi @Agaba-derrick I would like to work on this.
