### ISSUE TITLE
[Cypress] Test Case Failure in patientEntry.cy.js

### ISSUE THREAD

**Issue by Ankit-Matth** [I-TECH-UW/OpenELIS-Global-2#950]
# Description
 The test case "**Add|Modify Patient page should appear with search field**" in the test suite "**Patient Search**" defined in the specs named **patientEntry.cy.js** failed because the PatientEntryPage title was changed from "_Add/Modify Patient_" to "_Add Or Modify Patient_" but this modification was not reflected in the test case. Some screenshots illustrating this issue are provided below:

![Patient Search -- AddModify Patient page should appear with search field (failed)](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/146843890/6784f8de-8d11-4d2e-9f6f-f89fb4675b77)

![Before](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/146843890/9aa06fc8-7a45-4e70-9fb7-223f0972a06e)

**Comment by manishjha-04** [comment]
Hey @Ankit-Matth  I have already fixed this in PR #946

**Comment by Ankit-Matth** [comment]
Sorry @manishjha-04, I didn't see it. I raised this issue by mistake.
