### ISSUE TITLE
Fix Responsiveness of order and report components

### ISSUE THREAD

**Issue by atulyadav745** [I-TECH-UW/OpenELIS-Global-2#990]
## Description:
Unexpected responsiveness issues in the following components. These components do not adjust appropriately to different viewport screen sizes. Users are experiencing layout distortions and difficulties in accessing essential information. Inconsistencies are observed across devices with varying screen resolutions.
## Screenshots:
Current Behavior:

Add Order page:(iPad view) width- 810px
![Screen Shot 2024-04-17 at 10 49 54](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/106299466/b0b43309-7279-44f4-910f-37beaf34ceaf)

Pateint Info :(iPad view) width- 810px
![Screenshot from 2024-04-17 12-37-17](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/106299466/9e1f202a-26c8-4d61-af24-b64122eba401)

Edit Order page :(iPad view) width- 810px
![Screen Shot 2024-04-17 at 12 22 52](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/106299466/0373694e-c015-43d8-9848-58dcf3017fa3)

Batch order entry :(iPad view) width- 810px
![Screenshot from 2024-04-17 12-23-22](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/106299466/f237055f-8fb2-4697-9bc3-197d71b3187a)

(iPad view) width- 810px
![Screenshot from 2024-04-17 12-27-34](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/106299466/49af3b41-8304-4c53-8ec7-6265b1ff5672)

(iPad view) width- 810px
![Screenshot from 2024-04-17 12-26-00](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/106299466/adf3be32-57aa-43d2-a993-25143e515525)

(iPad view) width- 810px
![Screenshot from 2024-04-17 12-24-31](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/106299466/d96c253e-09c4-4980-b6b6-473b93901122)

(iPad view) width- 810px
![Screenshot from 2024-04-17 12-24-16](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/106299466/58a228be-4572-4a72-b3b3-17d829e0a057)

@mozzy11 Sir, Please assign me this issue so I can make a PR to fix this. 
Thank you!

**Comment by mozzy11** [comment]
Thanks @atulyadav745
